services:
  it-portal:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: https://agcqvaoyewjhpwpobsnh.supabase.co
        VITE_SUPABASE_ANON_KEY: sb_publishable_B7YpQ8U8bSF3ca39cXq2gA_TpUsIs3w
    image: it-portal:latest
    container_name: it-portal-web
    ports:
      - "8080:8080"
    restart: always
